In [1]:
%load_ext rustdef

load rustdef


In [2]:
%rustdef depends ndarray

In [3]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Use previous build


In [4]:
import numpy as np

In [5]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

2.4


array([ 4.7 , 18.58,  4.96])

In [6]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

// mutable example
#[pyfunction]
fn mult_inline<'a>(a: f64, x: Numpy<'a, f64>) -> PyResult<()> {
    let mut x = x.as_mut_array()?;
    x *= a;
    Ok(())
}

Building..
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
   Compiling rustdef_cell_223214be387e17f0d75f7d167313b1e3fc95793e v0.1.0 (/Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/rustdef_cell_223214be387e17f0d75f7d167313b1e3fc95793e)
    Finished dev [unoptimized + debuginfo] target(s) in 2.50s========> ] 65/66
📦 Built wheel for CPython 3.7m to /Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/target/wheels/rustdef_cell_223214be387e17f0d75f7d167313b1e3fc95793e-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl


In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.05457226, 0.03339249, 0.28366626, 0.53038699, 0.73687764,
        0.2330715 , 0.8534709 , 0.51477801, 0.43518456, 0.7717764 ]),
 array([0.92202829, 0.49670973, 0.08462944, 0.00731549, 0.89138919,
        0.66310512, 0.16123476, 0.70483545, 0.99116129, 0.61251495]))

In [8]:
axpy(3.0, x, y)

array([1.08574506, 0.5968872 , 0.93562823, 1.59847647, 3.10202212,
       1.36231961, 2.72164748, 2.24916947, 2.29671496, 2.92784414])

In [9]:
mult_inline(12.0, x)

In [10]:
x

array([ 0.65486708,  0.40070986,  3.40399514,  6.36464392,  8.8425317 ,
        2.79685798, 10.24165085,  6.1773361 ,  5.2222147 ,  9.26131676])