In [1]:
%load_ext rustdef

load rustdef


<IPython.core.display.Javascript object>

In [2]:
%rustdef depends --help

usage: %rustdef depends [-h] crates [crates ...]

Add crate dependencies

positional arguments:
  crates      Dependencies to be added

optional arguments:
  -h, --help  show this help message and exit


In [3]:
%rustdef depends ndarray

In [4]:
%%rustdef
use rustdef::numpy::Array;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Array<'a, f64>, y: Array<'a, f64>) -> PyResult<Array<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Use previous build


In [5]:
import numpy as np

In [6]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

2.4


array([ 4.7 , 18.58,  4.96])

In [7]:
%%rustdef
use rustdef::numpy::Array;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Array<'a, f64>, y: Array<'a, f64>) -> PyResult<Array<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

// mutable example
#[pyfunction]
fn mult_inline<'a>(a: f64, x: Array<'a, f64>) -> PyResult<()> {
    let mut x = x.into_mut_array()?;
    x *= a;
    Ok(())
}

Use previous build


In [8]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.19628029, 0.39215008, 0.75810141, 0.4340863 , 0.20076978,
        0.99568172, 0.51077557, 0.09887756, 0.88596831, 0.78325675]),
 array([0.46818721, 0.0326063 , 0.24154269, 0.5278223 , 0.22455559,
        0.42326449, 0.43476655, 0.66943576, 0.94854531, 0.44722263]))

In [9]:
axpy(3.0, x, y)

array([1.05702807, 1.20905655, 2.51584691, 1.83008121, 0.82686492,
       3.41030966, 1.96709325, 0.96606843, 3.60645024, 2.79699288])

In [10]:
mult_inline(12.0, x)

In [11]:
x

array([ 2.35536344,  4.70580097,  9.0972169 ,  5.20903565,  2.40923731,
       11.94818067,  6.12930679,  1.18653068, 10.63161974,  9.399081  ])