In [1]:
%load_ext rustdef

load rustdef


In [2]:
%rustdef depends ndarray

In [3]:
%%rustdef --force-rebuild
use rustdef::numpy::Array;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Array<'a, f64>, y: Array<'a, f64>) -> PyResult<Array<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Building..
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
   Compiling rustdef v0.1.0 (/Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/rustdef)
   Compiling rustdef_cell_90ca76e0b1b4a717af6b5fc54e3b7d961fa54e7e v0.1.0 (/Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/rustdef_cell_90ca76e0b1b4a717af6b5fc54e3b7d961fa54e7e)
    Finished release [optimized] target(s) in 6.38s==================> ] 79/80
📦 Built wheel for CPython 3.7m to /Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/target/wheels/rustdef_cell_90ca76e0b1b4a717af6b5fc54e3b7d961fa54e7e-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl


In [4]:
import numpy as np

In [5]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

2.4


array([ 4.7 , 18.58,  4.96])

In [6]:
%%rustdef
use rustdef::numpy::Array;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Array<'a, f64>, y: Array<'a, f64>) -> PyResult<Array<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

// mutable example
#[pyfunction]
fn mult_inline<'a>(a: f64, x: Array<'a, f64>) -> PyResult<()> {
    let mut x = x.as_mut_array()?;
    x *= a;
    Ok(())
}

Use previous build


In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.62699952, 0.4331902 , 0.40222644, 0.3673266 , 0.40515848,
        0.8509214 , 0.34669629, 0.16096525, 0.96889223, 0.34945816]),
 array([0.27548872, 0.61514319, 0.94372037, 0.86154525, 0.9077851 ,
        0.78505964, 0.64892413, 0.74064242, 0.99360506, 0.13073289]))

In [8]:
axpy(3.0, x, y)

array([2.15648728, 1.91471379, 2.15039968, 1.96352504, 2.12326056,
       3.33782385, 1.689013  , 1.22353816, 3.90028176, 1.17910738])

In [9]:
mult_inline(12.0, x)

In [10]:
x

array([ 7.52399422,  5.1982824 ,  4.82671723,  4.40791915,  4.86190181,
       10.21105684,  4.16035546,  1.93158297, 11.62670679,  4.19349794])