In [1]:
%load_ext rustdef

load rustdef


In [2]:
%rustdef depends ndarray

In [3]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Building..
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
   Compiling rustdef_cell_03588fbdb251b41d150db660c41300b0bcf8a211 v0.1.0 (/Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/rustdef_cell_03588fbdb251b41d150db660c41300b0bcf8a211)
    Finished release [optimized] target(s) in 5.69s==================> ] 65/66
📦 Built wheel for CPython 3.7m to /Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/target/wheels/rustdef_cell_03588fbdb251b41d150db660c41300b0bcf8a211-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl


In [4]:
import numpy as np

In [5]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

2.4


array([ 4.7 , 18.58,  4.96])

In [6]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

// mutable example
#[pyfunction]
fn mult_inline<'a>(a: f64, x: Numpy<'a, f64>) -> PyResult<()> {
    let mut x = x.as_mut_array()?;
    x *= a;
    Ok(())
}

Building..
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
   Compiling rustdef_cell_223214be387e17f0d75f7d167313b1e3fc95793e v0.1.0 (/Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/rustdef_cell_223214be387e17f0d75f7d167313b1e3fc95793e)
    Finished release [optimized] target(s) in 6.11s==================> ] 65/66
📦 Built wheel for CPython 3.7m to /Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/target/wheels/rustdef_cell_223214be387e17f0d75f7d167313b1e3fc95793e-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl


In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.14001574, 0.48651203, 0.36556508, 0.1352625 , 0.71307563,
        0.7740398 , 0.48816997, 0.23398476, 0.37298948, 0.77925944]),
 array([0.61308226, 0.95437294, 0.80421144, 0.57635468, 0.60616164,
        0.22449744, 0.75978381, 0.53582655, 0.25221966, 0.68476009]))

In [8]:
axpy(3.0, x, y)

array([1.03312948, 2.41390904, 1.90090668, 0.98214218, 2.74538854,
       2.54661685, 2.22429371, 1.23778085, 1.3711881 , 3.02253842])

In [9]:
mult_inline(12.0, x)

In [10]:
x

array([1.68018887, 5.8381444 , 4.38678096, 1.62314999, 8.55690762,
       9.28847763, 5.85803963, 2.80781717, 4.47587375, 9.3511133 ])