In [1]:
%load_ext rustdef

load rustdef


In [2]:
%rustdef depends ndarray

In [10]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Building..
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
   Compiling rustdef_cell_03588fbdb251b41d150db660c41300b0bcf8a211 v0.1.0 (/Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/rustdef_cell_03588fbdb251b41d150db660c41300b0bcf8a211)
    Finished dev [unoptimized + debuginfo] target(s) in 4.44s========> ] 65/66
📦 Built wheel for CPython 3.7m to /Users/ryosuke.kamesawa/Develop/rustdef/examples/.rustdef/target/wheels/rustdef_cell_03588fbdb251b41d150db660c41300b0bcf8a211-0.1.0-cp37-cp37m-macosx_10_7_x86_64.whl


In [4]:
import numpy as np

In [11]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

array([ 4.7 , 18.58,  4.96])

In [6]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

#[pyfunction]
fn mult_inline<'a>(a: f64, x: Numpy<'a, f64>) -> PyResult<()> {
    let mut x = x.as_mut_array()?;
    x *= a;
    Ok(())
}

In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.99701274, 0.49825399, 0.14670357, 0.2547876 , 0.9488243 ,
        0.13399108, 0.97625598, 0.13905982, 0.35385467, 0.51901118]),
 array([0.37897084, 0.83750653, 0.66365192, 0.15153639, 0.89486123,
        0.03179882, 0.55451258, 0.53825443, 0.47705533, 0.23497526]))

In [8]:
axpy(3.0, x, y)

array([3.37000905, 2.33226849, 1.10376261, 0.91589919, 3.74133413,
       0.43377206, 3.48328053, 0.95543388, 1.53861934, 1.79200882])

In [9]:
mult_inline(12.0, x)
x

array([11.96415286,  5.97904783,  1.76044279,  3.05745121, 11.38589157,
        1.60789293, 11.71507181,  1.6687178 ,  4.24625602,  6.22813422])

In [12]:
import sys

In [14]:
sys.stdout

In [17]:
n = sys.stdout.write("pohe\n")

pohe


In [18]:
n

In [19]:
help(sys.stdout)

Help on OutStream in module ipykernel.iostream object:

class OutStream(io.TextIOBase)
 |  OutStream(session, pub_thread, name, pipe=None, echo=None)
 |  
 |  A file like object that publishes the stream to a 0MQ PUB socket.
 |  
 |  Output is handed off to an IO Thread
 |  
 |  Method resolution order:
 |      OutStream
 |      io.TextIOBase
 |      _io._TextIOBase
 |      io.IOBase
 |      _io._IOBase
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, session, pub_thread, name, pipe=None, echo=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  close(self)
 |      Flush and close the IO object.
 |      
 |      This method has no effect if the file is already closed.
 |  
 |  flush(self)
 |      trigger actual zmq send
 |      
 |      send will happen in the background thread
 |  
 |  set_parent(self, parent)
 |  
 |  writable(self)
 |      Return whether object was opened for writing.
 |      
 |      If False, write() w