In [1]:
%load_ext rustdef

load rustdef


In [2]:
%rustdef depends ndarray

In [3]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

In [4]:
import numpy as np

In [5]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

array([ 4.7 , 18.58,  4.96])

In [6]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

#[pyfunction]
fn mult_inline<'a>(a: f64, x: Numpy<'a, f64>) -> PyResult<()> {
    let mut x = x.as_mut_array()?;
    x *= a;
    Ok(())
}

In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.99701274, 0.49825399, 0.14670357, 0.2547876 , 0.9488243 ,
        0.13399108, 0.97625598, 0.13905982, 0.35385467, 0.51901118]),
 array([0.37897084, 0.83750653, 0.66365192, 0.15153639, 0.89486123,
        0.03179882, 0.55451258, 0.53825443, 0.47705533, 0.23497526]))

In [8]:
axpy(3.0, x, y)

array([3.37000905, 2.33226849, 1.10376261, 0.91589919, 3.74133413,
       0.43377206, 3.48328053, 0.95543388, 1.53861934, 1.79200882])

In [9]:
mult_inline(12.0, x)
x

array([11.96415286,  5.97904783,  1.76044279,  3.05745121, 11.38589157,
        1.60789293, 11.71507181,  1.6687178 ,  4.24625602,  6.22813422])