In [1]:
%load_ext rustdef

In [2]:
%rustdef depends --help

In [3]:
%rustdef depends ndarray numpy

In [4]:
%%rustdef
use numpy::{IntoPyArray, PyArrayDyn, PyReadonlyArrayDyn};
use ndarray::{ArrayD, ArrayViewD};

// immutable example
fn axpy_rs(a: f64, x: ArrayViewD<'_, f64>, y: ArrayViewD<'_, f64>) -> ArrayD<f64> {
    a * &x + &y
}

#[pyfn(m, "axpy")]
fn axpy<'py>(
    py: Python<'py>,
    a: f64,
    x: PyReadonlyArrayDyn<f64>,
    y: PyReadonlyArrayDyn<f64>,
) -> &'py PyArrayDyn<f64> {
    let x = x.as_array();
    let y = y.as_array();
    axpy_rs(a, x, y).into_pyarray(py)
}

Use previous build


In [5]:
import numpy as np

In [6]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

array([ 4.7 , 18.58,  4.96])

In [7]:
%%rustdef
use numpy::{IntoPyArray, PyArrayDyn, PyReadonlyArrayDyn};
use ndarray::{ArrayD, ArrayViewD};

// mutable example
#[pyfn(m, "mult_inline")]
fn mult_inline<'py>(_py: Python<'py>, a: f64, x: &'py PyArrayDyn<f64>) -> PyResult<()> {
    let mut x = unsafe { x.as_array_mut() };
    x *= a;
    Ok(())
}

Building..
🔗 Found pyo3 bindings
🐍 Found CPython 3.6m at python3.6
   Compiling rustdef_cell_eb290401c4e6e3348fa7a25c89d3386163589099 v0.1.0 (/Users/ryosuke.kamesawa/.rustdef/rustdef_cell_eb290401c4e6e3348fa7a25c89d3386163589099)
    Finished release [optimized] target(s) in 1.30s=================>  ] 52/53
📦 Built wheel for CPython 3.6m to /Users/ryosuke.kamesawa/.rustdef/target/wheels/rustdef_cell_eb290401c4e6e3348fa7a25c89d3386163589099-0.1.0-cp36-cp36m-macosx_10_7_x86_64.whl


In [8]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.22028245, 0.24305027, 0.39490205, 0.39612272, 0.19711848,
        0.65031284, 0.0793689 , 0.79990404, 0.9847672 , 0.16397183]),
 array([0.22365979, 0.12497596, 0.80552557, 0.07580793, 0.55788643,
        0.26836718, 0.10282968, 0.52494688, 0.87406694, 0.21565078]))

In [9]:
axpy(3.0, x, y)

array([0.88450714, 0.85412678, 1.99023172, 1.26417608, 1.14924188,
       2.2193057 , 0.34093638, 2.924659  , 3.82836855, 0.70756628])

In [10]:
mult_inline(12.0, x)

In [11]:
x

array([ 2.6433894 ,  2.91660327,  4.7388246 ,  4.75347259,  2.36542179,
        7.80375408,  0.95242682,  9.59884847, 11.81720643,  1.96766201])