In [1]:
%load_ext rustdef

load rustdef


<IPython.core.display.Javascript object>

In [2]:
%rustdef depends --help

usage: %rustdef depends [-h] crates [crates ...]

positional arguments:
  crates      Dependencies to be added

optional arguments:
  -h, --help  show this help message and exit


In [3]:
%rustdef depends ndarray

In [4]:
%%rustdef
use rustdef::numpy::Array;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Array<'a, f64>, y: Array<'a, f64>) -> PyResult<Array<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Use previous build


In [5]:
import numpy as np

In [6]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

array([ 4.7 , 18.58,  4.96])

In [7]:
%%rustdef
use rustdef::numpy::Array;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Array<'a, f64>, y: Array<'a, f64>) -> PyResult<Array<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

// mutable example
#[pyfunction]
fn mult_inline<'a>(a: f64, x: Array<'a, f64>) -> PyResult<()> {
    let mut x = x.into_mut_array()?;
    x *= a;
    Ok(())
}

Use previous build


In [8]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.75344265, 0.26472768, 0.24398465, 0.81782102, 0.20087524,
        0.43946668, 0.53761482, 0.26105965, 0.14227416, 0.36258783]),
 array([0.15821954, 0.44902339, 0.10167481, 0.51983534, 0.8276814 ,
        0.58854872, 0.83497476, 0.60897576, 0.71064481, 0.46772272]))

In [9]:
axpy(3.0, x, y)

array([2.41854749, 1.24320645, 0.83362876, 2.9732984 , 1.4303071 ,
       1.90694878, 2.44781922, 1.39215472, 1.13746728, 1.55548622])

In [10]:
mult_inline(12.0, x)

In [11]:
x

array([9.04131182, 3.17673221, 2.92781579, 9.81385221, 2.41050283,
       5.27360021, 6.45137785, 3.13271583, 1.70728988, 4.351054  ])