In [1]:
%load_ext rustdef

load rustdef


In [2]:
%rustdef depends ndarray

In [3]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    println!("{}", a);
    Ok(z.into())
}

Use previous build


In [4]:
import numpy as np

In [5]:
axpy(2.4, np.array([1.0, 3.2, 2.9]), np.array([2.3, 10.9, -2]))

2.4


array([ 4.7 , 18.58,  4.96])

In [6]:
%%rustdef
use rustdef::Numpy;

// immutable example
#[pyfunction]
fn axpy<'a>(a: f64, x: Numpy<'a, f64>, y: Numpy<'a, f64>) -> PyResult<Numpy<'a, f64>> {
    let x = x.to_array();
    let y = y.to_array();
    let z = a * x + y;
    Ok(z.into())
}

// mutable example
#[pyfunction]
fn mult_inline<'a>(a: f64, x: Numpy<'a, f64>) -> PyResult<()> {
    let mut x = x.as_mut_array()?;
    x *= a;
    Ok(())
}

Use previous build


In [7]:
x = np.random.rand(10)
y = np.random.rand(10)
x, y

(array([0.35620347, 0.18658317, 0.5269757 , 0.23630135, 0.57454736,
        0.05540604, 0.15215006, 0.84340496, 0.00318686, 0.63748062]),
 array([0.5988546 , 0.40530163, 0.03063127, 0.59007521, 0.78762734,
        0.20007472, 0.544951  , 0.41126285, 0.61589392, 0.55434138]))

In [8]:
axpy(3.0, x, y)

array([1.66746501, 0.96505113, 1.61155837, 1.29897927, 2.51126941,
       0.36629285, 1.00140118, 2.94147774, 0.62545451, 2.46678323])

In [9]:
mult_inline(12.0, x)

In [10]:
x

array([ 4.27444164,  2.23899798,  6.32370842,  2.83561621,  6.89456828,
        0.66487253,  1.82580071, 10.12085953,  0.03824233,  7.64976742])